#=================================#
#  Magnet V1.0 - Configuration File
#=================================#

on-enable: "[Magnet] has been enabled"
on-disable: "[Magnet] has been disabled"
config-reload: "[Magnet] Configuration reloaded."
no-permission: '&3[&6&lMagnet&3] &CYou do not have permission to use this command.'
toggle-message: '&3[&6&lMagnet&3] &7You have &6{state} &7{module}.'
help: '&3[&6&lMagnet&3] &7Commands: &6/magnet, /magnet reload, /magnet help'
magnet-range: 8