name: magnet
version: '${project.version}'
main: com.chalwk.Magnet
api-version: '1.20'
authors: [ chalwk ]
description: Magnetize items toward you!
commands:
  magnet:
    description: Magnetize items toward you!
    usage: /<command>
    aliases: [ mag ]

permissions:
  magnet.*:
    description: Gives access to all Magnet commands
    default: op
    children:
      magnet.use: true
      magnet.reload: true
  magnet.use:
    description: Gives access to Magnet command
    default: op
  magnet.reload:
    description: Gives access to Magnet reload command
    default: op