options:
  auto-update: true
  debug: false
item-settings:
  smelters-shovel:
    cooldown: 500

messages:
  items:
    blaze-gun:
      no-ammo: "&cYou need &b{item_name} &cto shoot!"
    zapper-gun:
      no-ammo: "&cYou need &b{item_name} &cto shoot!"
    smelters-shovel:
      block-break: "&cYou cannot smelt this block!"
      damageable: true
