options:
  auto-update: true
  debug: false

item-settings:
  smelters-shovel:
    uses: 128
  blaze-gun:
    uses: 15
  zapper-gun:
    uses: 25

messages:
  items:
    blaze-gun:
      name: "&6Blaze Gun"
      description: "&bShoots burning magma cream!"
      no-ammo: "&cYou need &b{item_name} &cto shoot!"
      broke: "&cTool broke!"
      boss-bar: "Ues left: &b{uses} &7/ &b{max_uses}"
      damageable: true
    blaze-gun-ammo:
      name: "&6Blaze Gun Ammo"
      description: "&bAmmo for the Blaze Gun!"
    zapper-gun:
      name: "&6Zapper Gun"
      description: "Strikes lightning on your enemies"
      no-ammo: "&cYou need &b{item_name} &cto shoot!"
      broke: "&cTool broke!"
      boss-bar: "Ues left: &b{uses} &7/ &b{max_uses}"
      damageable: true
    zapper-gun-ammo:
      name: "&6Zapper Gun Ammo"
      description: "&bAmmo for the Zapper Gun!"
    smelters-shovel:
      name: "&6Smelters Shovel"
      description: "&bSmelts sand into glass!"
      broke: "&cTool broke!"
      boss-bar: "Ues left: &b{uses} &7/ &b{max_uses}"
      damageable: true
    sponge:
      name: "&6Sponge"
      description: "&bAbsorbs water!"