name: JCSpecials
author: Chalwk
description: Adds new weapons to the Slimefun4 plugin.
main: com.chalwk.JCSpecials
website: https://github.com/Chalwk77/JeriCraft-Plugins/tree/main/JCSpecials
version: ${project.version}
api-version: 1.14
depend:
  - Slimefun

commands:
  jcspecials_reload:
    description: Reloads the plugin
    permission: jcspecials.reload
    usage: /<command>

permissions:
  jcspecials.reload:
    description: Allows the player to reload the plugin
    default: op