name: Perks
version: '${project.version}'
main: com.chalwk.Perks
api-version: '1.20'
authors: [ Chalwk ]
description: Shows a player a list of perks they have purchased.
commands:
  perks:
    description: Shows a player a list of perks they have purchased.
    usage: "/<command> [show/reload]"