#========================================#
#  Big Brother V1.0 - Configuration File
#========================================#

on-enable: "[BigBrother] has been enabled"
on-disable: "[BigBrother] has been disabled"

# Required in order to use /bigbrother:
primary-permission: 'bigbrother.use'

# Message omitted when (this) configuration is reload:
config-reload: "&3[&6&lBig Brother&3] &aConfiguration has been reloaded"

# Required permission node to reload (this) configuration:
reload-permission: "bigbrother.reload"

# Message omitted when a player doesn't have permission to execute (any) BigBrother command:
no-permission: '&3[&6&lBig Brother&3] &cYou do not have permission to use this command.'

invalid-module: "&3[&6&lBig Brother&3] &cInvalid module. &7Valid modules: &6commands, signs, anvils, books, social"

# Messages omitted when an admin toggles a module:
toggle-message: '&3[&6&lBig Brother&3] &7You have &6{state} &7{module}.'
toggle-other: '&3[&6&lBig Brother&3] &7You have &6{state} &7{module} for &6{player}&7.'
invalid-player: '&3[&6&lBig Brother&3] &cInvalid player.'


#================================================================#
command-spy:
  notification: '&3[&6&lCMD SPY&3] &7{player}: &7{cmd}'
  toggle-permission: 'bigbrother.commandspy.toggle'
  toggle-others-permission: 'bigbrother.commandspy.toggle.others'
  hidden:
    - "/msg"
    - "/reply"
    - "/cmi msg"
    - "/cmi reply"
#================================================================#


#================================================================#
sign-spy:
  notification: "&3[&6&lSIGN SPY&3] &7{player}: \n&7{line1}\n&7{line2}\n&7{line3}\n&7{line4}"
  toggle-permission: 'bigbrother.signspy.toggle'
  toggle-others-permission: 'bigbrother.signspy.toggle.others'
#================================================================#


#================================================================#
anvil-spy:
  notification: "&3[&6&lANVIL SPY&3] &7{player} renamed &b{item} &7to &b{newname}"
  toggle-permission: 'bigbrother.anvilspy.toggle'
  toggle-others-permission: 'bigbrother.anvilspy.toggle.others'
#================================================================#


#================================================================#
book-spy:
  notification: "&3[&6&lBOOK SPY&3] &7{player}: &7{text}"
  toggle-permission: 'bigbrother.bookspy.toggle'
  toggle-others-permission: 'bigbrother.bookspy.toggle.others'
#================================================================#


#================================================================#
social-spy:
  notification: "&3[&6&lSOCIAL SPY&3] &7{player}: {cmd}"
  toggle-permission: 'bigbrother.socialspy.toggle'
  toggle-others-permission: 'bigbrother.socialspy.toggle.others'
  trigger-commands:
    - "/msg"
    - "/reply"
    - "/cmi msg"
    - "/cmi reply"
#================================================================#