name: BigBrother
version: '${project.version}'
main: com.chalwk.BigBrother
api-version: '1.20'
authors: [ chalwk ]
Description: Big Brother is watching you!
Commands:
  bigbrother:
    description: Big Brother is watching you!
    usage: /<command>
    aliases: [ bb ]